---
title: "Day Two Agenda"
author: "Ali Zaidi"
date: "September 21, 2016"
output:
  revealjs::revealjs_presentation:
    reveal_options:
      previewLinks: yes
      slideNumber: yes
      css: ../slides.css

    reveal_plugins:
    - zoom
    - notes
    self_contained: no
    theme: night
    transition: default
---

# Welcome Back!

## Day Two Agenda

### Topics

* Microsoft R Server Overview Presentation: _9:30 - 10:30_
* Hands-On Lab, Developing R Functions, Functional Programming: _10:45 - 12:00_
* The `dplyrXdf` Package: Using `dplyr` Syntax with `xdf`s: _12:45 - 1:45_
* Modeling and Scoring with Microsoft R Server, with Hands on Lab: _2:00 - 3:15_
* `RML`: The Microsoft Machine Learning Package for R, _3:30 - 4:45_

##  Morning Session

### Learning Objectives

* Microsoft R Server Overview Presentation: _9:30 - 10:30_
    - Learn how MRS breaks the memory barrier of R
    - Know what are the core components of MRS
    - Understand how PEMA works
* Hands-On Lab, Developing R Functions, Functional Programming: _10:45 - 12:00_
    - Understand why functions are useful
    - What it takes to make a good function
    - Why functionals are cool
    
# Lunch!!

## Afternoon Session

### Learning Objectives

* The `dplyrXdf` Package: Using `dplyr` Syntax with `xdf`s: _12:45 - 1:45_
    - How you can use your `dplyr` expertise to manipulate `xdf` files
    - When _not_ to use `dplyrXdf`
* Modeling and Scoring with Microsoft R Server, with Hands on Lab: _2:00 - 3:15_
    - Be able to estiimate models with MRS
    - Create functional pipelines for modeling, evaluation, and scoring
* `RML`: The Microsoft Machine Learning Package for R, _3:30 - 4:45_
    - Learn about the cutting-edge machine learning algorithms coming to MRS
    - Create a natural language processing model with `RML`
    
# Go home and write R!

